### ISSUE TITLE
Unable to import the angular-file-saver

### ISSUE THREAD

**Issue by ferryarman** [alferov/angular-file-saver#7]
Hi Philipp,

I tried to include your library on my Angular app (note: I'm using Webpack):
```javascript
import angularFileSaver from '../../node_modules/angular-file-saver/dist/angular-file-saver';
```
I was receiving this warning message on the Chrome Dev console:

```javascript
./~/angular-file-saver/dist/angular-file-saver.js
Critical dependencies:
1:113-120 This seems to be a pre-built javascript file. Though this is possible, it is not recommended. Try to require the original source to get better results.
 @ ./~/angular-file-saver/dist/angular-file-saver.js 1:113-120
```
And, this following error message:

```javascript
Error: saveAs is not supported. Please include saveAs polyfill
    at Object.FileSaverUtils.handleErrors (webpack:///./~/angular-file-saver/dist/angular-file-saver.js?:96:13)
    at Object.SaveAs (webpack:///./~/angular-file-saver/dist/angular-file-saver.js?:84:20)
    at Object.invoke (webpack:///./~/angular/angular.js?:4478:17)
    at Object.enforcedReturnValue [as $get] (webpack:///./~/angular/angular.js?:4330:37)
    at Object.invoke (webpack:///./~/angular/angular.js?:4478:17)
    at eval (webpack:///./~/angular/angular.js?:4295:37)
    at getService (webpack:///./~/angular/angular.js?:4437:39)
    at Object.invoke (webpack:///./~/angular/angular.js?:4469:13)
    at Object.enforcedReturnValue [as $get] (webpack:///./~/angular/angular.js?:4330:37)
    at Object.invoke (webpack:///./~/angular/angular.js?:4478:17) <div ui-view="nested" class="ng-scope">
```

Initially, I thought I need to explicitly include these 2 dependency libs:
import blob from '../../node_modules/angular-file-saver/node_modules//Blob.js/Blob';
import fileSaver from '../../node_modules/angular-file-saver/node_modules/FileSaver.js/FileSaver.min';

But, the above messages still appeared.

Any advice ?

-Ferdinand Arman

**Comment by alferov** [comment]
Hi, you can import the source file actually:
```js
import angularFileSaver from '../../node_modules/angular-file-saver/src/angular-file-saver-bundle.module';
```
This file imports all required dependencies.
Or simply:
```js
import angularFileSaver from 'angular-file-saver';
```
Webpack looks for dependencies in `node_modules` by default.

**Comment by alferov** [comment]
Fixed in https://github.com/alferov/angular-file-saver/releases/tag/1.1.0

**Comment by apatinoyu** [comment]
I get the same error back : saveAs is not supported. Please include saveAs polyfill
I am using: angular-file-saver 1.1.0

**Comment by shankspt** [comment]
I have installed angular-file-saver '1.1.1' and i still get the same error "Error: saveAs is not supported. Please include saveAs polyfill".

I included the following dependencies as you describe:

```
<script src="bower_components/angular-file-saver/dist/angular-file-saver.bundle.min.js"></script>
<script src="bower_components/angular-file-saver/dist/angular-file-saver.min.js"></script>
```

**Comment by monossido** [comment]
For me solved using
`"bower_components/angular-file-saver/dist/angular-file-saver.bundle.js"`
instead of
 `"bower_components/angular-file-saver/dist/angular-file-saver.js"`

**Comment by ashish-agarwal24** [comment]
I am facing the same problem. Added this line in index.html

`    <script src="bower_components/angular-file-saver/dist/angular-file-saver.bundle.js" />`

**Comment by wangjunxin** [comment]
I just include the file
`<script src="bower_components/angular-file-saver/dist/angular-file-saver.bundle.js" />`
and ngFileSaver worked
